### ISSUE TITLE
Moving away from unveil.js?

### ISSUE THREAD

**Issue by alexwilson** [Novactive/NovaeZResponsiveImagesBundle#1]
Hey,

I was wondering if there was any interest in moving away from unveil.js to something without a dependency on jQuery? (i.e. something like [echojs](https://github.com/toddmotto/echo))
Happy to submit a PR if so :)

Cheers!
Alex.

**Comment by Plopix** [comment]
Hello @antoligy,

Why not! if the feature is the same (or better) I don't see why we should not!
It could also be an option for the user, if it has jQuery already it might be better for him to choose.
Then please, don't hesitate to contribute! 
;-)
