### ISSUE TITLE
Ability to import polyfill from other sources?

### ISSUE THREAD

**Issue by alexwilson** [Novactive/NovaeZResponsiveImagesBundle#2]
Hey,

I was wondering if it's planned to allow moving the picturefill polyfill to be included elsewhere (i.e. https://polyfill.io), or to be included conditionally?  Like with the other issue, happy to submit a PR along those lines if so.

Cheers!
Alex.

**Comment by Plopix** [comment]
Again, don't hesitate, and yes I think we should do something where the user of this bundle has a way to choose what he wants in the configuration.
